// A CONTINUACIÓN LOS MISMOS DATOS, PERO SEPARADOS EN 2 OBJETOS.
// ESTE ES IDEAL PARA CARGAR EN LA BASE DE DATOS.
const reservationCabins = [
	{
		cabinId: 101,
		reservationId: 1,
		adults: 2,
		childrens: 0,
		mainGuest: "Daniel Jimenez",
		datesHotTub: [new Date(2025, 1, 3), new Date(2025, 1, 4)],
		priceCabin: 160_000,
		priceHotTub: 90_000,
	},
	{
		cabinId: 102,
		reservationId: 2,
		adults: 2,
		childrens: 0,
		mainGuest: "Hector Mendoza",
		datesHotTub: [new Date(2025, 1, 6)],
		priceCabin: 183_800,
		priceHotTub: 60_000,
	},
	{
		cabinId: 101,
		reservationId: 3,
		adults: 2,
		childrens: 0,
		mainGuest: "Juan Ruiz",
		datesHotTub: [],
		priceCabin: 643_300,
		priceHotTub: 0,
	},
	{
		cabinId: 102,
		reservationId: 4,
		adults: 1,
		childrens: 1,
		mainGuest: "Patricio Mena",
		datesHotTub: [new Date(2025, 1, 11), new Date(2025, 1, 12)],
		priceCabin: 183_800,
		priceHotTub: 90_000,
	},
	{
		cabinId: 103,
		reservationId: 5,
		adults: 1,
		childrens: 1,
		mainGuest: "Luis Cardenas",
		datesHotTub: [],
		priceCabin: 367_600,
		priceHotTub: 0,
	},
	{
		cabinId: 201,
		reservationId: 6,
		adults: 2,
		childrens: 2,
		mainGuest: "Ruben Jimenez",
		datesHotTub: [new Date(2025, 1, 10)],
		priceCabin: 482_700,
		priceHotTub: 60_000,
	},
	{
		cabinId: 202,
		reservationId: 7,
		adults: 3,
		childrens: 1,
		mainGuest: "Alexander Perez",
		datesHotTub: [new Date(2025, 1, 11)],
		priceCabin: 482_700,
		priceHotTub: 60_000,
	},
	{
		cabinId: 203,
		reservationId: 7,
		adults: 3,
		childrens: 1,
		mainGuest: "Ximena Navarrete",
		datesHotTub: [],
		priceCabin: 482_700,
		priceHotTub: 0,
	},
	{
		cabinId: 204,
		reservationId: 7,
		adults: 2,
		childrens: 2,
		mainGuest: "Dayana Escuadro",
		datesHotTub: [],
		priceCabin: 482_700,
		priceHotTub: 0,
	},
	{
		cabinId: 205,
		reservationId: 8,
		adults: 4,
		childrens: 0,
		mainGuest: "Mathew Cyr",
		datesHotTub: [new Date(2025, 1, 11), new Date(2025, 1, 12), new Date(2025, 1, 15)],
		priceCabin: 804_500,
		priceHotTub: 180_000,
	},
	{
		cabinId: 206,
		reservationId: 9,
		adults: 4,
		childrens: 0,
		mainGuest: "Mandy Scott",
		datesHotTub: [new Date(2025, 1, 9), new Date(2025, 1, 12)],
		priceCabin: 643_600,
		priceHotTub: 120_000,
	},
	{
		cabinId: 207,
		reservationId: 9,
		adults: 2,
		childrens: 2,
		mainGuest: "Billy Mandy",
		datesHotTub: [new Date(2025, 1, 12)],
		priceCabin: 643_600,
		priceHotTub: 60_000,
	},
	{
		cabinId: 208,
		reservationId: 10,
		adults: 4,
		childrens: 0,
		mainGuest: "Patrick Liu",
		datesHotTub: [],
		priceCabin: 482_700,
		priceHotTub: 0,
	},
	{
		cabinId: 209,
		reservationId: 10,
		adults: 3,
		childrens: 0,
		mainGuest: "Ho Chi Min",
		datesHotTub: [],
		priceCabin: 482_700,
		priceHotTub: 0,
	},
	{
		cabinId: 210,
		reservationId: 11,
		adults: 2,
		childrens: 2,
		mainGuest: "Sayid Mohammed",
		datesHotTub: [new Date(2025, 1, 8), new Date(2025, 1, 13)],
		priceCabin: 965_400,
		priceHotTub: 120_000,
	},
	{
		cabinId: 102,
		reservationId: 11,
		adults: 2,
		childrens: 0,
		mainGuest: "Doña Florinda",
		datesHotTub: [new Date(2025, 1, 8), new Date(2025, 1, 13)],
		priceCabin: 551_400,
		priceHotTub: 90_000,
	},
];

const reservations = [
	{
		documentTypeClient: "RUT",
		documentNumberClient: "14790916-0",
		nameClient: "Maria Sol Gordo",
		countryOfResidence: "Chile",
		phoneClient: "+56956102829",
		emailClient: "maria.sol.gordo@hotmail.com",
		checkinDate: new Date(2025, 1, 3),
		checkoutDate: new Date(2025, 1, 5), 
		statusReservation: "Completada",
		totalPrice: 250_000,
		notes: "Precios son más bajos, porque los precios subieron el 06/02",
	},
	{
		documentTypeClient: "Pasaporte",
		documentNumberClient: "11527374-P",
		nameClient: "Abderrahim Miranda",
		countryOfResidence: "País Vasco",
		phoneClient: "+9454827499",
		emailClient: "abderrahim.miranda@hotmail.com",
		checkinDate: new Date(2025, 1, 6),
		checkoutDate: new Date(2025, 1, 8),
		statusReservation: "Completada",
		totalPrice: 228_800,
		notes: "",
	},
	{
		documentTypeClient: "Pasaporte",
		documentNumberClient: "44628399-P",
		nameClient: "Jose Pablo Marcos",
		countryOfResidence: "Uruguay",
		phoneClient: "+59839462754",
		emailClient: "jose.pablo.marcos@hotmail.com",
		checkinDate: new Date(2025, 1, 6),
		checkoutDate: new Date(2025, 1, 13),
		statusReservation: "Confirmada",
		totalPrice: 643_300,
		notes: "",
	},
	{
		documentTypeClient: "RUT",
		documentNumberClient: "12329970-1",
		nameClient: "Lorena Bustamante",
		countryOfResidence: "Chile",
		phoneClient: "+56956102829",
		emailClient: "lorena.bustamante@hotmail.com",
		checkinDate: new Date(2025, 1, 17),
		checkoutDate: new Date(2025, 1, 19),
		statusReservation: "Confirmada",
		totalPrice: 273_800,
		notes: "",
	},
	{
		documentTypeClient: "Pasaporte",
		documentNumberClient: "93746154-L",
		nameClient: "Gaizka Molero",
		countryOfResidence: "España",
		phoneClient: "+349A8242552",
		emailClient: "gaizka.molero@hotmail.com",
		checkinDate: new Date(2025, 1, 10),
		checkoutDate: new Date(2025, 1, 14),
		statusReservation: "Confirmada",
		totalPrice: 367_600,
		notes: "",
	},
	{
		documentTypeClient: "Pasaporte",
		documentNumberClient: "02916749-L",
		nameClient: "Salma Cobo",
		countryOfResidence: "España",
		phoneClient: "+349A9313425",
		emailClient: "salma.cobo@hotmail.com",
		checkinDate: new Date(2025, 1, 10),
		checkoutDate: new Date(2025, 1, 13),
		statusReservation: "Confirmada",
		totalPrice: 542_700,
		notes: "",
	},
	{
		documentTypeClient: "RUT",
		documentNumberClient: "18592325-8",
		nameClient: "Bernat Freire",
		countryOfResidence: "Chile",
		phoneClient: "+56956102829",
		emailClient: "bernat.freire@hotmail.com",
		checkinDate: new Date(2025, 1, 11),
		checkoutDate: new Date(2025, 1, 14),
		statusReservation: "Confirmada",
		totalPrice: 1_508_100,
		notes: "",
	},
	{
		documentTypeClient: "Pasaporte",
		documentNumberClient: "12345678-L",
		nameClient: "Yanzhen Lou",
		countryOfResidence: "China",
		phoneClient: "130-8462-4710",
		emailClient: "yanzhen.lou@hotmail.com",
		checkinDate: new Date(2025, 1, 11),
		checkoutDate: new Date(2025, 1, 16),
		statusReservation: "Confirmada",
		totalPrice: 984_500,
		notes: "",
	},
	{
		documentTypeClient: "Pasaporte",
		documentNumberClient: "84027563-L",
		nameClient: "Jere Lawson",
		countryOfResidence: "EEUU",
		phoneClient: "+1(408) 453-2425",
		emailClient: "jere.lawson123@hotmail.com",
		checkinDate: new Date(2025, 1, 9),
		checkoutDate: new Date(2025, 1, 13),
		statusReservation: "Confirmada",
		totalPrice: 1_467_200,
		notes: "",
	},
	{
		documentTypeClient: "RUT",
		documentNumberClient: "24018888-0",
		nameClient: "Mario Cespedes",
		countryOfResidence: "Chile",
		phoneClient: "+56956102829",
		emailClient: "mario.cespedes.corto@hotmail.com",
		checkinDate: new Date(2025, 1, 10),
		checkoutDate: new Date(2025, 1, 13),
		statusReservation: "Confirmada",
		totalPrice: 965_400,
		notes: "",
	},
	{
		documentTypeClient: "RUT",
		documentNumberClient: "14790916-0",
		nameClient: "Angela Maria Santos",
		countryOfResidence: "Chile",
		phoneClient: "+56956102829",
		emailClient: "angel.mari.santo@hotmail.com",
		checkinDate: new Date(2025, 1, 8),
		checkoutDate: new Date(2025, 1, 14),
		statusReservation: "Confirmada",
		totalPrice: 1_726_800,
		notes: "",
	},
];

const cabins = [
	{
		typeName: "Tiny Cabin",
		number: 201,
		statusCabin: "Activa",
		statusHotTub: "Activa",
		reservedDates: [new Date(2025, 1, 3), new Date(2025, 1, 4), new Date(2025, 1, 6), new Date(2025, 1, 7), new Date(2025, 1, 8), new Date(2025, 1, 9), new Date(2025, 1, 10), new Date(2025, 1, 11), new Date(2025, 1, 12)],
		maxAdults: 2,
		maxChildrens: 3,
		capacity: 4,
		priceHotTubPerInstance: 60_000,
		pricePerNight: 160_900,
		amenities: [
      "Cocina", 
      "Aire Acondicionado",
      "Baño Privado (Ducha, Secador de pelo)",
      "Tinaja Caliente (costo adicional por uso)",
      "Toallas",
      "Estacionamiento Gratuito",
    ],
		size: 25,
		bedType: "1 Cama Queen + 2 Literas",
	},
	{
		typeName: "Tiny Cabin",
		number: 202,
		statusCabin: "Activa",
		statusHotTub: "Activa",
		reservedDates: [new Date(2025, 1, 6), new Date(2025, 1, 7), new Date(2025, 1, 8), new Date(2025, 1, 9), new Date(2025, 1, 10), new Date(2025, 1, 11), new Date(2025, 1, 12), new Date(2025, 1, 13), new Date(2025, 1, 17), new Date(2025, 1, 18)],
		maxAdults: 2,
		maxChildrens: 3,
		capacity: 4,
		priceHotTubPerInstance: 60_000,
		pricePerNight: 160_900,
		amenities: [
      "Cocina", 
      "Aire Acondicionado",
      "Baño Privado (Ducha, Secador de pelo)",
      "Tinaja Caliente (costo adicional por uso)",
      "Toallas",
      "Estacionamiento Gratuito",
    ],
		size: 25,
		bedType: "1 Cama Queen + 2 Literas",
	},
	{
		typeName: "Tiny Cabin",
		number: 203,
		statusCabin: "Activa",
		statusHotTub: "Activa",
		reservedDates: [new Date(2025, 1, 10), new Date(2025, 1, 11), new Date(2025, 1, 12), new Date(2025, 1, 13)],
		maxAdults: 2,
		maxChildrens: 3,
		capacity: 4,
		priceHotTubPerInstance: 60_000,
		pricePerNight: 160_900,
		amenities: [
      "Cocina", 
      "Aire Acondicionado",
      "Baño Privado (Ducha, Secador de pelo)",
      "Tinaja Caliente (costo adicional por uso)",
      "Toallas",
      "Estacionamiento Gratuito",
    ],
		size: 25,
		bedType: "1 Cama Queen + 2 Literas",
	},
	{
		typeName: "Tiny Cabin",
		number: 204,
		statusCabin: "Inactiva",
		statusHotTub: "Activa",
		reservedDates: [],
		maxAdults: 2,
		maxChildrens: 3,
		capacity: 4,
		priceHotTubPerInstance: 60_000,
		pricePerNight: 160_900,
		amenities: [
      "Cocina", 
      "Aire Acondicionado",
      "Baño Privado (Ducha, Secador de pelo)",
      "Tinaja Caliente (costo adicional por uso)",
      "Toallas",
      "Estacionamiento Gratuito",
    ],
		size: 25,
		bedType: "1 Cama Queen + 2 Literas",
	},
	{
		typeName: "Tiny Cabin",
		number: 205,
		statusCabin: "Inactiva",
		statusHotTub: "Activa",
		reservedDates: [],
		maxAdults: 2,
		maxChildrens: 3,
		capacity: 4,
		priceHotTubPerInstance: 60_000,
		pricePerNight: 160_900,
		amenities: [
      "Cocina", 
      "Aire Acondicionado",
      "Baño Privado (Ducha, Secador de pelo)",
      "Tinaja Caliente (costo adicional por uso)",
      "Toallas",
      "Estacionamiento Gratuito",
    ],
		size: 25,
		bedType: "1 Cama Queen + 2 Literas",
	},
	{
		typeName: "Tiny Cabin",
		number: 206,
		statusCabin: "Inactiva",
		statusHotTub: "Activa",
		reservedDates: [],
		maxAdults: 2,
		maxChildrens: 3,
		capacity: 4,
		priceHotTubPerInstance: 60_000,
		pricePerNight: 160_900,
		amenities: [
      "Cocina", 
      "Aire Acondicionado",
      "Baño Privado (Ducha, Secador de pelo)",
      "Tinaja Caliente (costo adicional por uso)",
      "Toallas",
      "Estacionamiento Gratuito",
    ],
		size: 25,
		bedType: "1 Cama Queen + 2 Literas",
	},
	{
		typeName: "Tiny Cabin",
		number: 207,
		statusCabin: "Inactiva",
		statusHotTub: "Activa",
		reservedDates: [],
		maxAdults: 2,
		maxChildrens: 3,
		capacity: 4,
		priceHotTubPerInstance: 60_000,
		pricePerNight: 160_900,
		amenities: [
      "Cocina", 
      "Aire Acondicionado",
      "Baño Privado (Ducha, Secador de pelo)",
      "Tinaja Caliente (costo adicional por uso)",
      "Toallas",
      "Estacionamiento Gratuito",
    ],
		size: 25,
		bedType: "1 Cama Queen + 2 Literas",
	},
	{
		typeName: "Tiny Cabin",
		number: 208,
		statusCabin: "Inactiva",
		statusHotTub: "Activa",
		reservedDates: [],
		maxAdults: 2,
		maxChildrens: 3,
		capacity: 4,
		priceHotTubPerInstance: 60_000,
		pricePerNight: 160_900,
		amenities: [
      "Cocina", 
      "Aire Acondicionado",
      "Baño Privado (Ducha, Secador de pelo)",
      "Tinaja Caliente (costo adicional por uso)",
      "Toallas",
      "Estacionamiento Gratuito",
    ],
		size: 25,
		bedType: "1 Cama Queen + 2 Literas",
	},
	{
		typeName: "Tiny Cabin",
		number: 209,
		statusCabin: "Inactiva",
		statusHotTub: "Activa",
		reservedDates: [],
		maxAdults: 2,
		maxChildrens: 3,
		capacity: 4,
		priceHotTubPerInstance: 60_000,
		pricePerNight: 160_900,
		amenities: [
      "Cocina", 
      "Aire Acondicionado",
      "Baño Privado (Ducha, Secador de pelo)",
      "Tinaja Caliente (costo adicional por uso)",
      "Toallas",
      "Estacionamiento Gratuito",
    ],
		size: 25,
		bedType: "1 Cama Queen + 2 Literas",
	},
	{
		typeName: "Tiny Cabin",
		number: 210,
		statusCabin: "Inactiva",
		statusHotTub: "Activa",
		reservedDates: [],
		maxAdults: 2,
		maxChildrens: 3,
		capacity: 4,
		priceHotTubPerInstance: 60_000,
		pricePerNight: 160_900,
		amenities: [
      "Cocina", 
      "Aire Acondicionado",
      "Baño Privado (Ducha, Secador de pelo)",
      "Tinaja Caliente (costo adicional por uso)",
      "Toallas",
      "Estacionamiento Gratuito",
    ],
		size: 25,
		bedType: "1 Cama Queen + 2 Literas",
	},
	{
		typeName: "Couple Room",
		number: 101,
		statusCabin: "Activa",
		statusHotTub: "Activa",
		reservedDates: [new Date(2025, 1, 10), new Date(2025, 1, 11), new Date(2025, 1, 12)],
		maxAdults: 2,
		maxChildrens: 1,
		capacity: 2,
		priceHotTubPerInstance: 45_000,
		pricePerNight: 91_900,
		amenities: [
      "Aire Acondicionado",
      "Baño Privado (Ducha, Secador de pelo)",
      "Tinaja Caliente (costo adicional por uso)",
      "Toallas",
      "Estacionamiento Gratuito",
    ],
		size: 14,
		bedType: "1 Cama Queen",
	},
	{
		typeName: "Couple Room",
		number: 102,
		statusCabin: "Activa",
		statusHotTub: "Activa",
		reservedDates: [new Date(2025, 1, 11), new Date(2025, 1, 12), new Date(2025, 1, 13)],
		maxAdults: 2,
		maxChildrens: 1,
		capacity: 2,
		priceHotTubPerInstance: 45_000,
		pricePerNight: 91_900,
		amenities: [
      "Aire Acondicionado",
      "Baño Privado (Ducha, Secador de pelo)",
      "Tinaja Caliente (costo adicional por uso)",
      "Toallas",
      "Estacionamiento Gratuito",
    ],
		size: 14,
		bedType: "1 Cama Queen",
	},
	{
		typeName: "Couple Room",
		number: 103,
		statusCabin: "Activa",
		statusHotTub: "Activa",
		reservedDates: [new Date(2025, 1, 11), new Date(2025, 1, 12), new Date(2025, 1, 13)],
		maxAdults: 2,
		maxChildrens: 1,
		capacity: 2,
		priceHotTubPerInstance: 45_000,
		pricePerNight: 91_900,
		amenities: [
      "Aire Acondicionado",
      "Baño Privado (Ducha, Secador de pelo)",
      "Tinaja Caliente (costo adicional por uso)",
      "Toallas",
      "Estacionamiento Gratuito",
    ],
		size: 14,
		bedType: "1 Cama Queen",
	},
	{
		typeName: "Couple Room",
		number: 104,
		statusCabin: "Activa",
		statusHotTub: "Activa",
		reservedDates: [new Date(2025, 1, 11), new Date(2025, 1, 12), new Date(2025, 1, 13)],
		maxAdults: 2,
		maxChildrens: 1,
		capacity: 2,
		priceHotTubPerInstance: 45_000,
		pricePerNight: 91_900,
		amenities: [
      "Aire Acondicionado",
      "Baño Privado (Ducha, Secador de pelo)",
      "Tinaja Caliente (costo adicional por uso)",
      "Toallas",
      "Estacionamiento Gratuito",
    ],
		size: 14,
		bedType: "1 Cama Queen",
	},
	{
		typeName: "Couple Room",
		number: 105,
		statusCabin: "Activa",
		statusHotTub: "Activa",
		reservedDates: [new Date(2025, 1, 11), new Date(2025, 1, 12), new Date(2025, 1, 13), new Date(2025, 1, 14), new Date(2025, 1, 15)],
		maxAdults: 2,
		maxChildrens: 1,
		capacity: 2,
		priceHotTubPerInstance: 45_000,
		pricePerNight: 91_900,
		amenities: [
      "Aire Acondicionado",
      "Baño Privado (Ducha, Secador de pelo)",
      "Tinaja Caliente (costo adicional por uso)",
      "Toallas",
      "Estacionamiento Gratuito",
    ],
		size: 14,
		bedType: "1 Cama Queen",
	},
	{
		typeName: "Couple Room",
		number: 106,
		statusCabin: "Activa",
		statusHotTub: "Activa",
		reservedDates: [new Date(2025, 1, 9), new Date(2025, 1, 10), new Date(2025, 1, 11), new Date(2025, 1, 12)],
		maxAdults: 2,
		maxChildrens: 1,
		capacity: 2,
		priceHotTubPerInstance: 45_000,
		pricePerNight: 91_900,
		amenities: [
      "Aire Acondicionado",
      "Baño Privado (Ducha, Secador de pelo)",
      "Tinaja Caliente (costo adicional por uso)",
      "Toallas",
      "Estacionamiento Gratuito",
    ],
		size: 14,
		bedType: "1 Cama Queen",
	},
	{
		typeName: "Couple Room",
		number: 107,
		statusCabin: "Activa",
		statusHotTub: "Activa",
		reservedDates: [new Date(2025, 1, 9), new Date(2025, 1, 10), new Date(2025, 1, 11), new Date(2025, 1, 12)],
		maxAdults: 2,
		maxChildrens: 1,
		capacity: 2,
		priceHotTubPerInstance: 45_000,
		pricePerNight: 91_900,
		amenities: [
      "Aire Acondicionado",
      "Baño Privado (Ducha, Secador de pelo)",
      "Tinaja Caliente (costo adicional por uso)",
      "Toallas",
      "Estacionamiento Gratuito",
    ],
		size: 14,
		bedType: "1 Cama Queen",
	},
	{
		typeName: "Couple Room",
		number: 108,
		statusCabin: "Activa",
		statusHotTub: "Activa",
		reservedDates: [new Date(2025, 1, 10), new Date(2025, 1, 11), new Date(2025, 1, 12)],
		maxAdults: 2,
		maxChildrens: 1,
		capacity: 2,
		priceHotTubPerInstance: 45_000,
		pricePerNight: 91_900,
		amenities: [
      "Aire Acondicionado",
      "Baño Privado (Ducha, Secador de pelo)",
      "Tinaja Caliente (costo adicional por uso)",
      "Toallas",
      "Estacionamiento Gratuito",
    ],
		size: 14,
		bedType: "1 Cama Queen",
	},
	{
		typeName: "Couple Room",
		number: 109,
		statusCabin: "Activa",
		statusHotTub: "Activa",
		reservedDates: [new Date(2025, 1, 10), new Date(2025, 1, 11), new Date(2025, 1, 12)],
		maxAdults: 2,
		maxChildrens: 1,
		capacity: 2,
		priceHotTubPerInstance: 45_000,
		pricePerNight: 91_900,
		amenities: [
      "Aire Acondicionado",
      "Baño Privado (Ducha, Secador de pelo)",
      "Tinaja Caliente (costo adicional por uso)",
      "Toallas",
      "Estacionamiento Gratuito",
    ],
		size: 14,
		bedType: "1 Cama Queen",
	},
	{
		typeName: "Couple Room",
		number: 110,
		statusCabin: "Activa",
		statusHotTub: "Activa",
		reservedDates: [new Date(2025, 1, 8), new Date(2025, 1, 9), new Date(2025, 1, 10), new Date(2025, 1, 11), new Date(2025, 1, 12), new Date(2025, 1, 13)],
		maxAdults: 2,
		maxChildrens: 1,
		capacity: 2,
		priceHotTubPerInstance: 45_000,
		pricePerNight: 91_900,
		amenities: [
      "Aire Acondicionado",
      "Baño Privado (Ducha, Secador de pelo)",
      "Tinaja Caliente (costo adicional por uso)",
      "Toallas",
      "Estacionamiento Gratuito",
    ],
		size: 14,
		bedType: "1 Cama Queen",
	},
];

const data = {reservationCabins, reservations, cabins}

module.exports = data;